openapi: 3.0.0
info:
  title: Aviator
  description: Air fare booking service
  version: 1.0.0

servers:
  - url: /

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          example: 'email@gmail.com'
        password:
          type: string
          exmaple: 'Ss!#qwert'
        firstName: 
          type: string
          example: 'Joe'
        lastName:
          type: string
          example: 'Jason'
        birthday:
          type: string
          example: '1987-04-11'
        gender:
          type: string
          example: 'male'
        contacts:
          type: object
          exmaple:
            {
              "email": "email@gmail.com",
              "countryCode": "+7",
              "phone": "123456789"
            }
        currency:
          type: string
          example: "RUB"
        dateFormat:
          type: string
          example: "DD/MM/YYYY"
        cartsIds:
          type: array
          items: ["1234", "21345", "2354"]
        tripsIds:
          type: array
          items: ["asldkfj", "alskdfj", "laskfdj"]
      required:
        - email
        - password
    